### ISSUE TITLE
"See also" that guides users to related functions

### ISSUE THREAD

**Issue by exoego** [superruzafa/visual-scala-reference#4]
There are some comibinations of functions that are related to each other, e.g.

* `compose` and `andThen` in `Function`
* `drop | dropRight | dropWhile | take | takeRight | takeWhile` in `Collection`
* `head | headOption | last | lastOption` in `Collection`
* ...

I think adding a **see-also table** or something to each page would be helpful for readers, so that they can find related functions even if they don't know names of all functions.

Such goal could be realized by mentioning related function in page.
But I think it could be error-prone and tedious... especially when accounting translation into.
So it would be nicer if relations between functions are generated by Jekyl for all pages in all translations, in single source of truth, like `see-also.yml` or something like that.

```yaml
see-also:
  group1: [compose,andThen]
  group2: [drop,dropRight,dropWhile,take,takeRight,takeWhile]
  group3: [head,headOption,last,lastOption]
  ...
```

I don't know Jekyll much... it may have such feature ?
